import { PieceDefinition, SpecialAbility, Player, TimerPreset, TimerConfig, Language } from './types';

export const BOARD_ROWS = 10;
export const BOARD_COLS = 11;

export const PLAYERS: { [key: string]: Player } = {
  RED: '1. Oyuncu',
  BLUE: '2. Oyuncu',
};

// DIKKAT: bu iki liste src/server.ts'teki kopyalariyla BIREBIR ayni olmali.
// Sunucu hamleyi bunlara gore dogruluyor; ayrisirlarsa istemci gecerli gosterdigi
// bir hamleyi sunucu reddeder (ve hata mesaji ekranda gorunmez).
// Tarafsiz bant 4-6. sutunlar. Desen 180 DERECE DONME simetrik: (r,c) -> (9-r, 10-c).
// Ust ucta agac koridoru 4. sutunda (MAVI'nin yaninda), alt ucta 6. sutunda
// (KIRMIZI'nin yaninda); goller her ucta koridorun karsi tarafinda. Boylece iki
// oyuncu da kendi koridoruna yandan girebiliyor — ayna simetri olsaydi biri
// koridora yandan girerken digeri golleri dolasmak zorunda kalirdi.
export const LAKE_COORDS: { row: number, col: number }[] = [
  { row: 1, col: 5 }, { row: 1, col: 6 },
  { row: 2, col: 5 }, { row: 2, col: 6 },
  { row: 7, col: 4 }, { row: 7, col: 5 },
  { row: 8, col: 4 }, { row: 8, col: 5 },
];

// density yalnizca kac agac cizilecegini belirler; oyun kuralini etkilemez.
export const FOREST_COORDS: { row: number, col: number, density: number }[] = [
  { row: 0, col: 4, density: 3 }, { row: 1, col: 4, density: 2 }, { row: 2, col: 4, density: 3 },
  { row: 3, col: 4, density: 2 }, { row: 3, col: 6, density: 1 },
  { row: 4, col: 5, density: 3 },
  { row: 5, col: 5, density: 2 },
  { row: 6, col: 6, density: 2 },
  { row: 7, col: 6, density: 3 }, { row: 8, col: 6, density: 2 }, { row: 9, col: 6, density: 3 },
];

export const PIECE_DEFINITIONS: { [key: string]: Omit<PieceDefinition, 'count'> } = {
  'Mareşal': { name: 'Mareşal', rank: 10, special: null, movable: true },
  'General': { name: 'General', rank: 9, special: null, movable: true },
  'Albay': { name: 'Albay', rank: 8, special: null, movable: true },
  'Binbaşı': { name: 'Binbaşı', rank: 7, special: null, movable: true },
  'Yüzbaşı': { name: 'Yüzbaşı', rank: 6, special: null, movable: true },
  'Üsteğmen': { name: 'Üsteğmen', rank: 5, special: null, movable: true },
  'Teğmen': { name: 'Teğmen', rank: 4, special: null, movable: true },
  'Astsubay': { name: 'Astsubay', rank: 3, special: null, movable: true },
  'Er': { name: 'Er', rank: 2, special: null, movable: true },
  'İzci': { name: 'İzci', rank: 2, special: SpecialAbility.SCOUT, movable: true },
  'İstihkamcı': { name: 'İstihkamcı', rank: 1, special: SpecialAbility.MINER, movable: true },
  'Casus': { name: 'Casus', rank: 1, special: SpecialAbility.SPY, movable: true },
  'Bomba': { name: 'Bomba', rank: 11, special: null, movable: false },
  'Bayrak': { name: 'Bayrak', rank: 0, special: null, movable: false },
};

// Tas adlarinin GORUNEN karsiliklari.
// DIKKAT: PIECE_DEFINITIONS icindeki Turkce 'name' degeri islevsel bir kimliktir —
// hem istemci (Piece.tsx ikon secimi) hem SUNUCU (resolveCombat: name === "Bayrak" /
// "Bomba") ona gore karar verir. Bu yuzden saklanan ad ASLA cevrilmez; yalnizca
// ekranda gosterilen etiket bu tablodan gecirilir.
export const PIECE_LABELS: Record<Language, Record<string, string>> = {
  TR: {
    'Mareşal': 'Mareşal', 'General': 'General', 'Albay': 'Albay', 'Binbaşı': 'Binbaşı',
    'Yüzbaşı': 'Yüzbaşı', 'Üsteğmen': 'Üsteğmen', 'Teğmen': 'Teğmen', 'Astsubay': 'Astsubay',
    'Er': 'Er', 'İzci': 'İzci', 'İstihkamcı': 'İstihkamcı', 'Casus': 'Casus',
    'Bomba': 'Bomba', 'Bayrak': 'Bayrak',
  },
  EN: {
    'Mareşal': 'Marshal', 'General': 'General', 'Albay': 'Colonel', 'Binbaşı': 'Major',
    'Yüzbaşı': 'Captain', 'Üsteğmen': 'Lieutenant', 'Teğmen': 'Sergeant', 'Astsubay': 'Corporal',
    'Er': 'Private', 'İzci': 'Scout', 'İstihkamcı': 'Miner', 'Casus': 'Spy',
    'Bomba': 'Bomb', 'Bayrak': 'Flag',
  },
  JA: {
    'Mareşal': '元帥', 'General': '大将', 'Albay': '大佐', 'Binbaşı': '少佐',
    'Yüzbaşı': '大尉', 'Üsteğmen': '中尉', 'Teğmen': '軍曹', 'Astsubay': '伍長',
    'Er': '兵卒', 'İzci': '斥候', 'İstihkamcı': '工兵', 'Casus': 'スパイ',
    'Bomba': '地雷', 'Bayrak': '軍旗',
  },
  KO: {
    'Mareşal': '원수', 'General': '대장', 'Albay': '대령', 'Binbaşı': '소령',
    'Yüzbaşı': '대위', 'Üsteğmen': '중위', 'Teğmen': '중사', 'Astsubay': '상병',
    'Er': '이등병', 'İzci': '정찰병', 'İstihkamcı': '공병', 'Casus': '스파이',
    'Bomba': '지뢰', 'Bayrak': '군기',
  },
};

/** Tasin ekranda gosterilecek adi. Bilinmeyen ad gelirse kanonik adi dondurur. */
export const getPieceLabel = (name: string, lang: Language): string =>
  PIECE_LABELS[lang]?.[name] ?? PIECE_LABELS.TR[name] ?? name;

// Oyuncu basina TAM 40 tas — dizilim alani 4 sutun x 10 satir = 40 kare, bosluk
// birakmiyor. Bu tablonun toplami DEGISMEMELI; bir tasi artirirken digerini
// azaltmak sart (Izci 4->2 karsiliginda Er ve Bomba +1 alindi).
export const PIECE_COUNTS: { [key: string]: number } = {
  'Mareşal': 1,
  'General': 1,
  'Albay': 2,
  'Binbaşı': 3,
  'Yüzbaşı': 4,
  'Üsteğmen': 4,
  'Teğmen': 4,
  'Astsubay': 4,
  'Er': 5,
  // Izci sayisi 2: artik siradan bir tas degil, ISTIHBARAT kaynagi. Ilk kullanim
  // bedava, sonrasi SCOUT_COOLDOWN turluk bekleme (bkz. server.ts "scout").
  'İzci': 2,
  'İstihkamcı': 4,
  'Casus': 1,
  'Bomba': 4, // 4 Mayın
  'Bayrak': 1,
};

// Bir oyuncu süresi dolduğu için tur kaçırdığında sayacı artar. İKİ oyuncu da bu
// sınıra ulaşınca oyun berabere biter — kimse oynamıyorsa masayı boş bırakmamak için.
export const MAX_MISSED_TURNS = 3;

// Izci gorevini kullandiktan sonra hakkin yenilenmesi icin sahibinin oynamasi
// gereken tur sayisi. Ilk kullanim bedava. src/server.ts SCOUT_COOLDOWN ile
// AYNI olmali — sunucu karari veriyor, buradaki yalnizca arayuz metni icin.
export const SCOUT_COOLDOWN = 10;

export const TIMER_PRESETS: Record<TimerPreset, TimerConfig> = {
  FAST: { turnTime: 15, setupTime: 60, disconnectTime: 30 },
  NORMAL: { turnTime: 35, setupTime: 120, disconnectTime: 60 },
  LONG: { turnTime: 60, setupTime: 240, disconnectTime: 90 },
};

export const createInitialPiecePool = (): PieceDefinition[] => {
    const pool: PieceDefinition[] = [];
    for (const name in PIECE_COUNTS) {
        pool.push({
            ...PIECE_DEFINITIONS[name],
            count: PIECE_COUNTS[name],
        });
    }
    return pool;
};

export const LANGUAGES: { code: Language; name: string; flag: string }[] = [
  { code: 'TR', name: 'Türkçe', flag: '🇹🇷' },
  { code: 'EN', name: 'English', flag: '🇬🇧' },
  { code: 'JA', name: '日本語', flag: '🇯🇵' },
  { code: 'KO', name: '한국어', flag: '🇰🇷' },
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  TR: {
    appTitle: 'ASTACT',
    appSubtitle: 'Strateji ve Taktik Savaşı',
    gameInfoTitle: 'Oyun Bilgisi',
    capturedPieces: 'Ele Geçirilenler',
    piecePowers: 'Rütbe Hiyerarşisi',
    specialRules: 'Özel Kurallar',
    combatHistory: 'Çarpışma Geçmişi',
    noCombatYet: 'Henüz çarpışma olmadı.',
    randomSetup: 'Rastgele Diz',
    clearSetup: 'Temizle',
    readyButton: 'Dizilimi Onayla & Hazırım',
    waitingOpponent: 'Rakip dizilimi tamamlaması bekleniyor...',
    bothReady: 'İki taraf da hazır! Oyun Başlıyor...',
    timerPresetFast: 'Hızlı',
    timerPresetNormal: 'Normal',
    timerPresetLong: 'Uzun',
    turnTimer: 'Hamle Süresi',
    setupTimer: 'Dizilim Süresi',
    disconnectTimer: 'Kopma Süresi',
    seconds: 'sn',
    statsTitle: 'İstatistikler & Ayarlar',
    soundVolume: 'Müzik ve Ses Seviyesi',
    totalGames: 'Oynanan Oyun',
    redWins: '1. Oyuncu Galibiyet',
    blueWins: '2. Oyuncu Galibiyet',
    totalBattles: 'Çarpışma Sayısı',
    close: 'Kapat',
    onlineTitle: 'Çevrimiçi Oda',
    createRoom: 'Oda Oluştur',
    joinRoom: 'Odaya Katıl',
    roomCode: 'Oda Kodu',
    copyCode: 'Kodu Kopyala', codeCopied: 'Kod Kopyalandı!',
    enterCode: 'Oda kodunu girin',
    statusConnected: 'Bağlandı',
    statusWaiting: 'Oyuncu Bekleniyor...',
    spyRule: 'Casus (1) sadece Mareşal\'e (10) saldırırsa yener.',
    minerRule: 'İstihkamcı (1) Bombayı etkisiz hale getirir ve kareye geçer.',
    bombRule: 'Bomba üzerine gelen İstihkamcı dışındaki her taşı yok eder.',
    sameRankRule: 'Aynı rütbeler çarpışınca kimse ölmez, ikisi de yerinde kalır.',
    noBackwardRule: 'Geriye hareket etmek kesinlikle yasaktır!',
    playerRed: '1. Oyuncu', playerBlue: '2. Oyuncu', colorRed: 'Kırmızı', colorBlue: 'Mavi',
    rankWord: 'Rütbe',
    setupRedStatus: '1. Oyuncu Taşlarını Diziyor', setupBlueStatus: '2. Oyuncu Taşlarını Diziyor',
    turnRedStatus: 'Sıra: 1. Oyuncu (Kırmızı)', turnBlueStatus: 'Sıra: 2. Oyuncu (Mavi)',
    opponentWaiting: 'Rakip bekleniyor', opponentOffline: 'Rakibin bağlantısı koptu',
    opponentSettingUp: 'Rakip taşlarını diziyor', opponentReady: 'Rakip hazır — seni bekliyor',
    yourTurnStatus: 'Sıra sende', opponentTurnStatus: 'Sıra rakipte',
    gameOverStatus: 'Oyun Bitti!',
    combatMiner: 'İstihkamcı Bombayı imha etti ve kareye ilerledi!',
    combatSpy: 'Casus Mareşal’i avladı ve yerine geçti!',
    combatHigherWins: '{a} ({rw} {ar}) > {d} ({rw} {dr}) — Rütbesi büyük olan yendi ve yerine ilerledi!',
    combatFlagCaptured: '{a} Bayrağı ele geçirdi! ZAFER!',
    combatBombHit: '{a} Bombaya bastı ve patladı! Bomba sabit kaldı.',
    combatDefenderWins: '{d} ({rw} {dr}) daha yüksek — Saldıran {a} yok oldu, savunan yerinde kaldı.',
    combatEqualRank: 'Aynı rütbede ({ar}) çarpıştılar: İkisi de yerinde kaldı, geri dönmediler.',
    onlineButton: 'Online Oyun', roomLabel: 'Oda', youAre: 'Siz',
    connectedShort: 'Bağlı', disconnectedShort: 'Bağlantı Kesik',
    restartButton: 'Yeniden Başlat', statsButton: 'İstatistikler', timerPresetsLabel: 'Süre Ön Ayarları',
    settingsPanelTitle: 'Ayarlar', gameInfoPanelTitle: 'Oyun Bilgisi',
    timerLockedHint: 'Oyun başladı — süre ayarı kilitli.',
    timerHostOnlyHint: 'Online oyunda hamle süresini oda kurucusu belirler.',
    missedTurnsLabel: 'Kaçırılan Tur',
    drawHeading: 'BERABERE',
    drawTimeoutReason: 'İki oyuncu da {n} tur kaçırdı, oyun otomatik bitti.',
    setupPanelSuffix: 'Dizilim', allPlaced: 'Tüm taşlar dizildi!',
    allPlacedHint: 'Dizilimi tamamlayıp maça başlayabilirsiniz.',
    setupLocked: 'Diziliminiz Kilitlendi!', waitingOpponentSetup: 'Rakibinizin dizilimi tamamlaması bekleniyor...',
    statsHeading: 'ASKERİ TAKTİK İSTATİSTİKLERİ', statsSubtitle: 'Analitik & Müzik Ses Ayarları',
    bgMusicVolume: 'Arka Plan Müzik Sesi',
    onlineHeading: 'ONLINE ÇOK OYUNCULU MOD', onlineSubtitle: 'Oda Oluştur veya Oda Kodu ile Katıl',
    shareCodeHint: 'Bu kodu rakibinizle paylaşarak oyuna davet edin.',
    playerStatuses: 'Oyuncu Durumları', liveLabel: 'Canlı',
    onlineLabel: 'Çevrimiçi', offlineLabel: 'Çevrimdışı',
    waitingOpponentJoin: '⏳ Rakibinizin odaya katılması bekleniyor. Katıldığı an dizilime başlanacaktır.',
    bothReadyGoSetup: '⚔️ İki oyuncu hazır! Dizilim ekranına geçiliyor...',
    leaveRoom: 'Odayı Terk Et', playerNameOptional: 'Oyuncu Adınız (İsteğe Bağlı)',
    phNameRed: 'Örn. Komutan Kırmızı', phNameBlue: 'Örn. Komutan Mavi', phRoomCode: 'Örn. TAK-8492',
    newRoomButton: 'YENİ ODA OLUŞTUR', joinRoomButton: 'ODAYA KATIL',
    errRestartRequested: 'Rakip yeniden başlatma istedi. Onaylamak için Yeniden Başlat butonuna basın.',
    waitingRestartApproval: 'Yeniden başlatma isteğin gönderildi — rakibin onayı bekleniyor.',
    errConnectionLost: 'Bağlantı koptu.', errWsError: 'WebSocket bağlantı hatası.',
    errRoomCreateFailed: 'Oda oluşturulamadı.',
    errNOT_YOUR_TURN: 'Sıra rakibinizde.', errINVALID_MOVE: 'Geçersiz hamle.',
    errPIECE_NOT_FOUND: 'Taş bulunamadı.', errPIECE_IMMOBILE: 'Bu taş hareket edemez.',
    errBACKWARD: 'Geriye hareket yasak!', errONE_SQUARE: 'Sadece bir kare hareket edilebilir.',
    errSTRAIGHT_ONLY: 'Sadece düz hareket edilebilir.', errOUT_OF_BOUNDS: 'Tahta dışına çıkılamaz.',
    errLAKE: 'Göl üzerine gidilemez.', errOWN_PIECE: 'Orada kendi taşınız var.',
    errSERVER_ERROR: 'Sunucu hatası.', errROOM_FULL: 'Oda dolu veya oyun çoktan başladı.',
    errSCOUT_NOT_SCOUT: 'Bu görevi yalnızca İzci yapabilir.',
    errSCOUT_COOLDOWN: 'Bu İzci {n} hamle sonra tekrar kullanılabilir.',
    errSCOUT_RANGE: 'İzci yalnızca kendi satırındaki düşman taşını görebilir.',
    errSCOUT_LAKE: 'Önünde göl var — görüş kapalı.',
    errSCOUT_FOREST: 'Ormandaki taşın kimliği görülemez.',
    winnerLabel: 'Kazanan', youBadge: '(Siz)',
    victoryHeading: 'ZAFER!', defeatHeading: 'YENİLDİN',
    victoryFlag: 'Rakibin bayrağını ele geçirdin. Cephe senin!',
    defeatFlag: 'Bayrağın düştü. Rakip cepheyi ele geçirdi.',
    victoryOpponentLeft: 'Rakip oyuna geri dönmedi — hükmen kazandın.',
    defeatYouLeft: 'Bağlantın çok uzun süre koptuğu için oyunu kaybettin.',
    drawTitleShort: 'Berabere bitti.',
    opponentDisconnectedTitle: 'Rakibin bağlantısı koptu',
    opponentDisconnectedWait: 'Geri dönmesi bekleniyor — {n} sn içinde dönmezse oyunu sen kazanırsın.',
    opponentReconnected: 'Rakip yeniden bağlandı, oyun kaldığı yerden sürüyor.',
    youDisconnectedTitle: 'Bağlantın koptu',
    youDisconnectedWait: 'Yeniden bağlanılıyor — {n} sn içinde dönmezsen oyunu kaybedersin.',
    youReconnected: 'Yeniden bağlandın.',
  },
  EN: {
    appTitle: 'ASTACT',
    appSubtitle: 'A Battle of Strategy and Tactics',
    gameInfoTitle: 'Game Info',
    capturedPieces: 'Captured Pieces',
    piecePowers: 'Rank Hierarchy',
    specialRules: 'Special Rules',
    combatHistory: 'Combat Log',
    noCombatYet: 'No combat yet.',
    randomSetup: 'Random Placement',
    clearSetup: 'Clear',
    readyButton: 'Confirm Setup & Ready',
    waitingOpponent: 'Waiting for opponent to finish setup...',
    bothReady: 'Both ready! Battle Begins...',
    timerPresetFast: 'Fast',
    timerPresetNormal: 'Normal',
    timerPresetLong: 'Long',
    turnTimer: 'Turn Time',
    setupTimer: 'Setup Time',
    disconnectTimer: 'Disconnect Time',
    seconds: 's',
    statsTitle: 'Stats & Settings',
    soundVolume: 'Audio & Music Volume',
    totalGames: 'Games Played',
    redWins: 'Player 1 Wins',
    blueWins: 'Player 2 Wins',
    totalBattles: 'Total Battles',
    close: 'Close',
    onlineTitle: 'Online Room',
    createRoom: 'Create Room',
    joinRoom: 'Join Room',
    roomCode: 'Room Code',
    copyCode: 'Copy Code', codeCopied: 'Code Copied!',
    enterCode: 'Enter room code',
    statusConnected: 'Connected',
    statusWaiting: 'Waiting for player...',
    spyRule: 'Spy (1) defeats Marshal (10) only when attacking.',
    minerRule: 'Miner (1) disarms the Bomb and moves forward.',
    bombRule: 'Bomb destroys any piece that hits it except Miner.',
    sameRankRule: 'Equal ranks collide: nobody dies, both stay in place.',
    noBackwardRule: 'Moving backward is strictly forbidden!',
    playerRed: 'Player 1', playerBlue: 'Player 2', colorRed: 'Red', colorBlue: 'Blue',
    rankWord: 'Rank',
    setupRedStatus: 'Player 1 is placing pieces', setupBlueStatus: 'Player 2 is placing pieces',
    turnRedStatus: 'Turn: Player 1 (Red)', turnBlueStatus: 'Turn: Player 2 (Blue)',
    opponentWaiting: 'Waiting for an opponent', opponentOffline: 'Your opponent disconnected',
    opponentSettingUp: 'Opponent is placing pieces', opponentReady: 'Opponent ready — waiting for you',
    yourTurnStatus: 'Your turn', opponentTurnStatus: 'Opponent’s turn',
    gameOverStatus: 'Game Over!',
    combatMiner: 'The Miner defused the Bomb and advanced!',
    combatSpy: 'The Spy struck down the Marshal and took its place!',
    combatHigherWins: '{a} ({rw} {ar}) > {d} ({rw} {dr}) — the higher rank won and advanced!',
    combatFlagCaptured: '{a} captured the Flag! VICTORY!',
    combatBombHit: '{a} stepped on the Bomb and was destroyed! The Bomb stayed put.',
    combatDefenderWins: '{d} ({rw} {dr}) is higher — the attacking {a} was destroyed, the defender held.',
    combatEqualRank: 'Equal rank ({ar}) clash: both stayed in place, neither retreated.',
    onlineButton: 'Online Game', roomLabel: 'Room', youAre: 'You',
    connectedShort: 'Connected', disconnectedShort: 'Disconnected',
    restartButton: 'Restart', statsButton: 'Statistics', timerPresetsLabel: 'Timer Presets',
    settingsPanelTitle: 'Settings', gameInfoPanelTitle: 'Game Info',
    timerLockedHint: 'Game started — timer settings locked.',
    timerHostOnlyHint: 'In online games the room host sets the turn time.',
    missedTurnsLabel: 'Missed Turns',
    drawHeading: 'DRAW',
    drawTimeoutReason: 'Both players missed {n} turns — the game ended automatically.',
    setupPanelSuffix: 'Setup', allPlaced: 'All pieces placed!',
    allPlacedHint: 'Confirm your setup to start the match.',
    setupLocked: 'Your setup is locked!', waitingOpponentSetup: 'Waiting for your opponent to finish their setup...',
    statsHeading: 'MILITARY TACTICS STATISTICS', statsSubtitle: 'Analytics & Music Volume',
    bgMusicVolume: 'Background Music Volume',
    onlineHeading: 'ONLINE MULTIPLAYER', onlineSubtitle: 'Create a room or join with a code',
    shareCodeHint: 'Share this code with your opponent to invite them.',
    playerStatuses: 'Player Status', liveLabel: 'Live',
    onlineLabel: 'Online', offlineLabel: 'Offline',
    waitingOpponentJoin: '⏳ Waiting for your opponent to join. Setup begins the moment they do.',
    bothReadyGoSetup: '⚔️ Both players ready! Moving to the setup screen...',
    leaveRoom: 'Leave Room', playerNameOptional: 'Your Name (Optional)',
    phNameRed: 'e.g. Red Commander', phNameBlue: 'e.g. Blue Commander', phRoomCode: 'e.g. TAK-8492',
    newRoomButton: 'CREATE NEW ROOM', joinRoomButton: 'JOIN ROOM',
    errRestartRequested: 'Your opponent requested a restart. Press Restart to confirm.',
    waitingRestartApproval: 'Restart requested — waiting for your opponent to confirm.',
    errConnectionLost: 'Connection lost.', errWsError: 'WebSocket connection error.',
    errRoomCreateFailed: 'Could not create the room.',
    errNOT_YOUR_TURN: 'It is your opponent’s turn.', errINVALID_MOVE: 'Invalid move.',
    errPIECE_NOT_FOUND: 'Piece not found.', errPIECE_IMMOBILE: 'This piece cannot move.',
    errBACKWARD: 'Moving backward is forbidden!', errONE_SQUARE: 'Only one square at a time.',
    errSTRAIGHT_ONLY: 'Only straight moves are allowed.', errOUT_OF_BOUNDS: 'Cannot move off the board.',
    errLAKE: 'Cannot move onto a lake.', errOWN_PIECE: 'Your own piece is there.',
    errSERVER_ERROR: 'Server error.', errROOM_FULL: 'The room is full or the game already started.',
    errSCOUT_NOT_SCOUT: 'Only the Scout can do this.',
    errSCOUT_COOLDOWN: 'This Scout can be used again in {n} moves.',
    errSCOUT_RANGE: 'The Scout can only see an enemy piece on its own row.',
    errSCOUT_LAKE: 'A lake blocks the line of sight.',
    errSCOUT_FOREST: 'A piece in the forest cannot be identified.',
    winnerLabel: 'Winner', youBadge: '(You)',
    victoryHeading: 'VICTORY!', defeatHeading: 'DEFEATED',
    victoryFlag: 'You captured the enemy flag. The field is yours!',
    defeatFlag: 'Your flag has fallen. The enemy took the field.',
    victoryOpponentLeft: 'Your opponent never came back — you win by forfeit.',
    defeatYouLeft: 'You lost the game because your connection stayed down too long.',
    drawTitleShort: 'The game ended in a draw.',
    opponentDisconnectedTitle: 'Your opponent lost connection',
    opponentDisconnectedWait: 'Waiting for them to return — if they do not within {n}s, you win.',
    opponentReconnected: 'Your opponent reconnected, the game continues.',
    youDisconnectedTitle: 'You lost connection',
    youDisconnectedWait: 'Reconnecting — if you do not return within {n}s, you lose the game.',
    youReconnected: 'You are back online.',
  },
  JA: {
    appTitle: 'ASTACT',
    appSubtitle: '戦略と戦術の戦い',
    gameInfoTitle: '対局情報',
    capturedPieces: '撃破した駒',
    piecePowers: '階級一覧',
    specialRules: '特殊ルール',
    combatHistory: '戦闘履歴',
    noCombatYet: 'まだ戦闘はありません。',
    randomSetup: 'ランダム配置',
    clearSetup: 'クリア',
    readyButton: '配置完了・準備完了',
    waitingOpponent: '相手の配置完了を待っています...',
    bothReady: '両者準備完了！戦闘開始...',
    timerPresetFast: '高速',
    timerPresetNormal: '通常',
    timerPresetLong: 'じっくり',
    turnTimer: '持ち時間',
    setupTimer: '配置時間',
    disconnectTimer: '切断猶予',
    seconds: '秒',
    statsTitle: '戦績と設定',
    soundVolume: '音量とBGM',
    totalGames: '対局数',
    redWins: 'プレイヤー1勝利',
    blueWins: 'プレイヤー2勝利',
    totalBattles: '総戦闘回数',
    close: '閉じる',
    onlineTitle: 'オンライン対戦',
    createRoom: 'ルーム作成',
    joinRoom: 'ルーム参加',
    roomCode: 'ルームコード',
    copyCode: 'コードをコピー', codeCopied: 'コピーしました！',
    enterCode: 'コードを入力',
    statusConnected: '接続完了',
    statusWaiting: '対戦相手を待っています...',
    spyRule: 'スパイ(1)は元帥(10)に攻撃した時のみ勝利します。',
    minerRule: '工兵(1)は地雷を解除して進みます。',
    bombRule: '地雷は工兵以外の攻撃駒をすべて破壊します。',
    sameRankRule: '同階級の衝突：誰も倒れず、その場にとどまります。',
    noBackwardRule: '後退移動は一切禁止されています！',
    playerRed: 'プレイヤー1', playerBlue: 'プレイヤー2', colorRed: '赤', colorBlue: '青',
    rankWord: '階級',
    setupRedStatus: 'プレイヤー1が配置中', setupBlueStatus: 'プレイヤー2が配置中',
    turnRedStatus: '手番: プレイヤー1（赤）', turnBlueStatus: '手番: プレイヤー2（青）',
    opponentWaiting: '相手を待っています', opponentOffline: '相手の接続が切れました',
    opponentSettingUp: '相手が配置中', opponentReady: '相手は準備完了 — あなた待ちです',
    yourTurnStatus: 'あなたの手番', opponentTurnStatus: '相手の手番',
    gameOverStatus: '対局終了！',
    combatMiner: '工兵が地雷を処理して前進した！',
    combatSpy: 'スパイが元帥を討ち取り、その位置に入った！',
    combatHigherWins: '{a}（{rw}{ar}）＞ {d}（{rw}{dr}）— 階級が上の駒が勝ち、前進した！',
    combatFlagCaptured: '{a}が軍旗を奪取！勝利！',
    combatBombHit: '{a}が地雷を踏んで撃破された！地雷はその場に残った。',
    combatDefenderWins: '{d}（{rw}{dr}）が上位 — 攻撃側の{a}は撃破され、守備側は残った。',
    combatEqualRank: '同階級（{ar}）の衝突: 双方その場に留まり、後退しなかった。',
    onlineButton: 'オンライン対戦', roomLabel: 'ルーム', youAre: 'あなた',
    connectedShort: '接続中', disconnectedShort: '切断',
    restartButton: '再開', statsButton: '統計', timerPresetsLabel: '持ち時間設定',
    settingsPanelTitle: '設定', gameInfoPanelTitle: 'ゲーム情報',
    timerLockedHint: '対局中は持ち時間を変更できません。',
    timerHostOnlyHint: 'オンライン対局では持ち時間を部屋の作成者が決めます。',
    missedTurnsLabel: '時間切れ回数',
    drawHeading: '引き分け',
    drawTimeoutReason: '両者が{n}回時間切れになったため、対局を自動終了しました。',
    setupPanelSuffix: '配置', allPlaced: 'すべての駒を配置しました！',
    allPlacedHint: '配置を確定して対局を開始できます。',
    setupLocked: '配置を確定しました！', waitingOpponentSetup: '相手の配置完了を待っています…',
    statsHeading: '戦術統計', statsSubtitle: '分析と音量設定',
    bgMusicVolume: 'BGM音量',
    onlineHeading: 'オンライン対戦モード', onlineSubtitle: 'ルームを作成、またはコードで参加',
    shareCodeHint: 'このコードを相手に共有して招待してください。',
    playerStatuses: 'プレイヤー状況', liveLabel: 'ライブ',
    onlineLabel: 'オンライン', offlineLabel: 'オフライン',
    waitingOpponentJoin: '⏳ 相手の参加を待っています。参加した時点で配置が始まります。',
    bothReadyGoSetup: '⚔️ 両者準備完了！配置画面へ移動します…',
    leaveRoom: 'ルームを退出', playerNameOptional: 'プレイヤー名（任意）',
    phNameRed: '例: 赤の指揮官', phNameBlue: '例: 青の指揮官', phRoomCode: '例: TAK-8492',
    newRoomButton: '新しいルームを作成', joinRoomButton: 'ルームに参加',
    errRestartRequested: '相手が再開を希望しています。「再開」を押して承認してください。',
    waitingRestartApproval: '再開をリクエストしました。相手の承認を待っています。',
    errConnectionLost: '接続が切れました。', errWsError: 'WebSocket接続エラー。',
    errRoomCreateFailed: 'ルームを作成できませんでした。',
    errNOT_YOUR_TURN: '相手の手番です。', errINVALID_MOVE: '無効な手です。',
    errPIECE_NOT_FOUND: '駒が見つかりません。', errPIECE_IMMOBILE: 'この駒は動けません。',
    errBACKWARD: '後退は禁止です！', errONE_SQUARE: '一マスずつしか動けません。',
    errSTRAIGHT_ONLY: '直線移動のみ可能です。', errOUT_OF_BOUNDS: '盤外には出られません。',
    errLAKE: '湖には入れません。', errOWN_PIECE: 'そこには自分の駒があります。',
    errSERVER_ERROR: 'サーバーエラー。', errROOM_FULL: '部屋が満員か、ゲームがすでに開始しています。',
    errSCOUT_NOT_SCOUT: 'これができるのは斥候だけです。',
    errSCOUT_COOLDOWN: 'この斥候はあと{n}手で再び使えます。',
    errSCOUT_RANGE: '斥候は同じ行の敵の駒しか見られません。',
    errSCOUT_LAKE: '湖に遮られて視界がありません。',
    errSCOUT_FOREST: '森の中の駒は識別できません。',
    winnerLabel: '勝者', youBadge: '（あなた）',
    victoryHeading: '勝利！', defeatHeading: '敗北',
    victoryFlag: '敵の旗を奪取した。戦場は君のものだ！',
    defeatFlag: '自軍の旗が落ちた。戦場は敵の手に。',
    victoryOpponentLeft: '相手が戻らなかったため、不戦勝です。',
    defeatYouLeft: '接続が長時間切れていたため、敗北となりました。',
    drawTitleShort: '引き分けで終了しました。',
    opponentDisconnectedTitle: '相手の接続が切れました',
    opponentDisconnectedWait: '復帰を待っています — {n}秒以内に戻らなければあなたの勝ちです。',
    opponentReconnected: '相手が再接続しました。ゲームを続行します。',
    youDisconnectedTitle: '接続が切れました',
    youDisconnectedWait: '再接続中 — {n}秒以内に戻らなければ敗北となります。',
    youReconnected: '再接続しました。',
  },
  KO: {
    appTitle: 'ASTACT',
    appSubtitle: '전략과 전술의 전쟁',
    gameInfoTitle: '게임 정보',
    capturedPieces: '포획한 기물',
    piecePowers: '계급 계층',
    specialRules: '특별 규칙',
    combatHistory: '전투 기록',
    noCombatYet: '아직 전투가 없습니다.',
    randomSetup: '무작위 배치',
    clearSetup: '초기화',
    readyButton: '배치 완료 및 준비',
    waitingOpponent: '상대방의 배치를 기다리는 중...',
    bothReady: '양측 준비 완료! 전투 시작...',
    timerPresetFast: '빠름',
    timerPresetNormal: '보통',
    timerPresetLong: '긴 시간',
    turnTimer: '턴 시간',
    setupTimer: '배치 시간',
    disconnectTimer: '연결 끊김 시간',
    seconds: '초',
    statsTitle: '통계 및 설정',
    soundVolume: '음량 및 배경음악',
    totalGames: '총 게임 수',
    redWins: '1플레이어 승리',
    blueWins: '2플레이어 승리',
    totalBattles: '전투 횟수',
    close: '닫기',
    onlineTitle: '온라인 방',
    createRoom: '방 만들기',
    joinRoom: '방 참가',
    roomCode: '방 코드',
    copyCode: '코드 복사', codeCopied: '코드가 복사되었습니다!',
    enterCode: '방 코드 입력',
    statusConnected: '연결됨',
    statusWaiting: '플레이어 대기 중...',
    spyRule: '첩보원(1)은 원수(10)에게 선제공격 시 승리합니다.',
    minerRule: '공병(1)은 지뢰를 해제하고 전진합니다.',
    bombRule: '지뢰는 공병을 제외한 공격 기물을 파괴합니다.',
    sameRankRule: '동급 계급 충돌: 아무도 죽지 않고 제자리에 남습니다.',
    noBackwardRule: '후퇴 이동은 엄격히 금지됩니다!',
    playerRed: '플레이어 1', playerBlue: '플레이어 2', colorRed: '적군', colorBlue: '청군',
    rankWord: '계급',
    setupRedStatus: '플레이어 1이 기물을 배치 중', setupBlueStatus: '플레이어 2가 기물을 배치 중',
    turnRedStatus: '차례: 플레이어 1 (적군)', turnBlueStatus: '차례: 플레이어 2 (청군)',
    opponentWaiting: '상대를 기다리는 중', opponentOffline: '상대의 연결이 끊겼습니다',
    opponentSettingUp: '상대가 기물을 배치 중', opponentReady: '상대 준비 완료 — 당신을 기다리는 중',
    yourTurnStatus: '내 차례', opponentTurnStatus: '상대 차례',
    gameOverStatus: '게임 종료!',
    combatMiner: '공병이 지뢰를 제거하고 전진했습니다!',
    combatSpy: '스파이가 원수를 제거하고 그 자리를 차지했습니다!',
    combatHigherWins: '{a} ({rw} {ar}) > {d} ({rw} {dr}) — 계급이 높은 쪽이 이기고 전진했습니다!',
    combatFlagCaptured: '{a}이 군기를 탈취했습니다! 승리!',
    combatBombHit: '{a}이 지뢰를 밟아 파괴되었습니다! 지뢰는 제자리에 남았습니다.',
    combatDefenderWins: '{d} ({rw} {dr})가 더 높습니다 — 공격한 {a}은 파괴되고 수비 측이 버텼습니다.',
    combatEqualRank: '동일 계급 ({ar}) 충돌: 둘 다 제자리에 남고 후퇴하지 않았습니다.',
    onlineButton: '온라인 대전', roomLabel: '방', youAre: '나',
    connectedShort: '연결됨', disconnectedShort: '연결 끊김',
    restartButton: '다시 시작', statsButton: '통계', timerPresetsLabel: '시간 설정',
    settingsPanelTitle: '설정', gameInfoPanelTitle: '게임 정보',
    timerLockedHint: '대국 중에는 시간 설정을 변경할 수 없습니다.',
    timerHostOnlyHint: '온라인 대국에서는 방장이 제한 시간을 정합니다.',
    missedTurnsLabel: '시간 초과 횟수',
    drawHeading: '무승부',
    drawTimeoutReason: '양쪽 모두 {n}회 시간 초과하여 대국이 자동 종료되었습니다.',
    setupPanelSuffix: '배치', allPlaced: '모든 기물을 배치했습니다!',
    allPlacedHint: '배치를 확정하고 대국을 시작할 수 있습니다.',
    setupLocked: '배치가 확정되었습니다!', waitingOpponentSetup: '상대의 배치 완료를 기다리고 있습니다…',
    statsHeading: '전술 통계', statsSubtitle: '분석 및 음량 설정',
    bgMusicVolume: '배경음악 음량',
    onlineHeading: '온라인 멀티플레이', onlineSubtitle: '방 만들기 또는 코드로 참가',
    shareCodeHint: '이 코드를 상대에게 공유해 초대하세요.',
    playerStatuses: '플레이어 상태', liveLabel: '실시간',
    onlineLabel: '온라인', offlineLabel: '오프라인',
    waitingOpponentJoin: '⏳ 상대의 참가를 기다리고 있습니다. 참가하면 배치가 시작됩니다.',
    bothReadyGoSetup: '⚔️ 두 플레이어 준비 완료! 배치 화면으로 이동합니다…',
    leaveRoom: '방 나가기', playerNameOptional: '플레이어 이름 (선택)',
    phNameRed: '예: 적군 지휘관', phNameBlue: '예: 청군 지휘관', phRoomCode: '예: TAK-8492',
    newRoomButton: '새 방 만들기', joinRoomButton: '방 참가',
    errRestartRequested: '상대가 재시작을 요청했습니다. 다시 시작을 눌러 승인하세요.',
    waitingRestartApproval: '재시작을 요청했습니다. 상대의 승인을 기다리는 중입니다.',
    errConnectionLost: '연결이 끊어졌습니다.', errWsError: 'WebSocket 연결 오류.',
    errRoomCreateFailed: '방을 만들 수 없습니다.',
    errNOT_YOUR_TURN: '상대의 차례입니다.', errINVALID_MOVE: '잘못된 이동입니다.',
    errPIECE_NOT_FOUND: '기물을 찾을 수 없습니다.', errPIECE_IMMOBILE: '이 기물은 움직일 수 없습니다.',
    errBACKWARD: '후퇴는 금지입니다!', errONE_SQUARE: '한 칸씩만 이동할 수 있습니다.',
    errSTRAIGHT_ONLY: '직선 이동만 가능합니다.', errOUT_OF_BOUNDS: '판 밖으로 나갈 수 없습니다.',
    errLAKE: '호수로는 갈 수 없습니다.', errOWN_PIECE: '거기에는 아군 기물이 있습니다.',
    errSERVER_ERROR: '서버 오류.', errROOM_FULL: '방이 가득 찼거나 게임이 이미 시작되었습니다.',
    errSCOUT_NOT_SCOUT: '이 임무는 정찰병만 수행할 수 있습니다.',
    errSCOUT_COOLDOWN: '이 정찰병은 {n}수 후에 다시 사용할 수 있습니다.',
    errSCOUT_RANGE: '정찰병은 같은 행의 적 기물만 볼 수 있습니다.',
    errSCOUT_LAKE: '호수에 가로막혀 시야가 없습니다.',
    errSCOUT_FOREST: '숲에 있는 기물은 식별할 수 없습니다.',
    winnerLabel: '승자', youBadge: '(나)',
    victoryHeading: '승리!', defeatHeading: '패배',
    victoryFlag: '적의 깃발을 빼앗았습니다. 전장은 당신의 것입니다!',
    defeatFlag: '아군의 깃발이 함락되었습니다. 전장을 적에게 내주었습니다.',
    victoryOpponentLeft: '상대가 돌아오지 않아 부전승으로 이겼습니다.',
    defeatYouLeft: '연결이 너무 오래 끊겨 패배했습니다.',
    drawTitleShort: '무승부로 끝났습니다.',
    opponentDisconnectedTitle: '상대의 연결이 끊겼습니다',
    opponentDisconnectedWait: '복귀를 기다리는 중 — {n}초 안에 돌아오지 않으면 당신이 승리합니다.',
    opponentReconnected: '상대가 다시 연결되어 게임이 계속됩니다.',
    youDisconnectedTitle: '연결이 끊겼습니다',
    youDisconnectedWait: '재연결 중 — {n}초 안에 돌아오지 않으면 패배합니다.',
    youReconnected: '다시 연결되었습니다.',
  }
};
